[unstable]
build-std = ["core","compiler_builtins"]

[build]
target = "arm-none-eabihf.json"

[target.'cfg(target_os = "none")']
runner = "qemu-system-arm -serial stdio -device isa-debug-exit,iobase=0xf4,iosize=0x04 -M raspi1ap -kernel"
